server:
  port: 8080
  
spring:
  datasource:
     url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:project_management_db}
     username: ${MYSQL_USERNAME:lehann}
     password: ${MYSQL_PASSWORD:lehannCronje1234}
  servlet:
    multipart:
      max-file-size:
        500MB
      max-request-size:
        500MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
